AWSTemplateFormatVersion: '2010-09-09'
Description: C6M3 task Template (create an EC2 instance, S3 bucket with SSM connect)

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: c6m3-bucket-test
  
  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - MyEC2Role

  MyEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyEC2Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04cb4ca688797756f
      InstanceType: t2.micro
      IamInstanceProfile: !Ref MyInstanceProfile
      Tags:
        - Key: Name
          Value: Cil-c6m3-instance

Outputs:
  InstanceId:
    Description: Instance ID of created EC2 instance
    Value: !Ref MyEC2Instance

  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
